
#define SW_UWSHCU_01
#ifdef SW_UWSHCU_01
    external :: slave_uwshcu_c1
    type param_uw_com_t1
      integer*8 :: zs0
      integer*8 :: ps0
      integer*8 :: p0
      integer*8 :: tke
      integer*8 :: thvl0bot
      integer*8 :: thvl0top
      integer*8 :: qt0
      integer*8 :: u0
      integer*8 :: ssu0
      integer*8 :: v0
      integer*8 :: ssv0
      integer*8 :: trsrc
      integer*8 :: thl0
      integer*8 :: ssthl0
      integer*8 :: ssqt0
      integer*8 :: thv0bot
      integer*8 :: thv0top
      integer*8 :: trsrc_o
      integer*8 :: qv0
      integer*8 :: qv0_o
      integer*8 :: ql0
      integer*8 :: ql0_o
      integer*8 :: qi0
      integer*8 :: qi0_o
      integer*8 :: t0
      integer*8 :: t0_o
      integer*8 :: s0
      integer*8 :: s0_o
      integer*8 :: u0_o
      integer*8 :: v0_o
      integer*8 :: qt0_o
      integer*8 :: thl0_o
      integer*8 :: thvl0
      integer*8 :: thvl0_o
      integer*8 :: ssthl0_o
      integer*8 :: ssqt0_o
      integer*8 :: thv0bot_o
      integer*8 :: thv0top_o
      integer*8 :: thvl0bot_o
      integer*8 :: thvl0top_o
      integer*8 :: ssu0_o
      integer*8 :: ssv0_o
      integer*8 :: umf
      integer*8 :: emf
      integer*8 :: slflx
      integer*8 :: qtflx
      integer*8 :: uflx
      integer*8 :: vflx
      integer*8 :: qvten
      integer*8 :: qlten
      integer*8 :: qiten
      integer*8 :: sten
      integer*8 :: uten
      integer*8 :: vten
      integer*8 :: qrten
      integer*8 :: qsten
      integer*8 :: dwten
      integer*8 :: diten
      integer*8 :: evapc
      integer*8 :: cufrc
      integer*8 :: qcu
      integer*8 :: qlu
      integer*8 :: qiu
      integer*8 :: fer
      integer*8 :: fdr
      integer*8 :: qc
      integer*8 :: qc_l
      integer*8 :: qc_i
      integer*8 :: qtten
      integer*8 :: slten
      integer*8 :: ufrc
      integer*8 :: thlu
      integer*8 :: qtu
      integer*8 :: uu
      integer*8 :: vu
      integer*8 :: wu
      integer*8 :: thvu
      integer*8 :: thlu_emf
      integer*8 :: qtu_emf
      integer*8 :: uu_emf
      integer*8 :: vu_emf
      integer*8 :: excessu_arr
      integer*8 :: excess0_arr
      integer*8 :: xc_arr
      integer*8 :: aquad_arr
      integer*8 :: bquad_arr
      integer*8 :: cquad_arr
      integer*8 :: bogbot_arr
      integer*8 :: bogtop_arr
      integer*8 :: umf_out
      integer*8 :: umf_s
      integer*8 :: qvten_out
      integer*8 :: qvten_s
      integer*8 :: qlten_out
      integer*8 :: qlten_s
      integer*8 :: qiten_out
      integer*8 :: qiten_s
      integer*8 :: sten_out
      integer*8 :: sten_s
      integer*8 :: uten_out
      integer*8 :: uten_s
      integer*8 :: vten_out
      integer*8 :: vten_s
      integer*8 :: qrten_out
      integer*8 :: qrten_s
      integer*8 :: qsten_out
      integer*8 :: qsten_s
      integer*8 :: evapc_out
      integer*8 :: evapc_s
      integer*8 :: cufrc_out
      integer*8 :: cufrc_s
      integer*8 :: slflx_out
      integer*8 :: slflx_s
      integer*8 :: qtflx_out
      integer*8 :: qtflx_s
      integer*8 :: qcu_out
      integer*8 :: qcu_s
      integer*8 :: qlu_out
      integer*8 :: qlu_s
      integer*8 :: qiu_out
      integer*8 :: qiu_s
      integer*8 :: qc_out
      integer*8 :: qc_s
      integer*8 :: fer_out
      integer*8 :: fer_s
      integer*8 :: fdr_out
      integer*8 :: fdr_s
      integer*8 :: qtten_out
      integer*8 :: qtten_s
      integer*8 :: slten_out
      integer*8 :: slten_s
      integer*8 :: ufrc_out
      integer*8 :: ufrc_s
      integer*8 :: uflx_out
      integer*8 :: uflx_s
      integer*8 :: vflx_out
      integer*8 :: vflx_s
      integer*8 :: wu_out
      integer*8 :: wu_s
      integer*8 :: qtu_out
      integer*8 :: qtu_s
      integer*8 :: thlu_out
      integer*8 :: thlu_s
      integer*8 :: thvu_out
      integer*8 :: thvu_s
      integer*8 :: uu_out
      integer*8 :: uu_s
      integer*8 :: vu_out
      integer*8 :: vu_s
      integer*8 :: qtu_emf_out
      integer*8 :: qtu_emf_s
      integer*8 :: thlu_emf_out
      integer*8 :: thlu_emf_s
      integer*8 :: uu_emf_out
      integer*8 :: uu_emf_s
      integer*8 :: vu_emf_out
      integer*8 :: vu_emf_s
      integer*8 :: uemf_out
      integer*8 :: uemf_s
      integer*8 :: dwten_out
      integer*8 :: dwten_s
      integer*8 :: diten_out
      integer*8 :: diten_s
      integer*8 :: flxrain_out
      integer*8 :: flxrain_s
      integer*8 :: flxsnow_out
      integer*8 :: flxsnow_s
      integer*8 :: ntraprd_out
      integer*8 :: ntraprd_s
      integer*8 :: ntsnprd_out
      integer*8 :: ntsnprd_s
      integer*8 :: excessu_arr_out
      integer*8 :: excessu_arr_s
      integer*8 :: excess0_arr_out
      integer*8 :: excess0_arr_s
      integer*8 :: xc_arr_out
      integer*8 :: xc_arr_s
      integer*8 :: aquad_arr_out
      integer*8 :: aquad_arr_s
      integer*8 :: bquad_arr_out
      integer*8 :: bquad_arr_s
      integer*8 :: cquad_arr_out
      integer*8 :: cquad_arr_s
      integer*8 :: bogbot_arr_out
      integer*8 :: bogbot_arr_s
      integer*8 :: bogtop_arr_out
      integer*8 :: bogtop_arr_s
      integer*8 :: exns0
      integer*8 :: dp0
      integer*8 :: write
      integer*8 :: tre
      integer*8 :: rei
      integer*8 :: exn0
      integer*8 :: xflx
      integer*8 :: uemf
      integer*8 :: comsub
      integer*8 :: nlten_sink
      integer*8 :: niten_sink
      integer*8 :: uf
      integer*8 :: vf
      integer*8 :: qlten_sink
      integer*8 :: qiten_sink
      integer*8 :: flxrain
      integer*8 :: flxsnow
      integer*8 :: ntraprd
      integer*8 :: ntsnprd
      integer*8 :: qw0_in
      integer*8 :: qv0_star
      integer*8 :: ql0_star
      integer*8 :: qi0_star
      integer*8 :: s0_star
      integer*8 :: trflx_d
      integer*8 :: trflx_u
      integer*8 :: dpdry0
      integer*8 :: qv0_s
      integer*8 :: ql0_s
      integer*8 :: qi0_s
      integer*8 :: s0_s
      integer*8 :: u0_s
      integer*8 :: v0_s
      integer*8 :: qt0_s
      integer*8 :: t0_s
      integer*8 :: flxprc1_out
      integer*8 :: flxsnow1_out
      integer*8 :: tr0
      integer*8 :: tr0_o
      integer*8 :: sstr0
      integer*8 :: sstr0_o
      integer*8 :: trflx
      integer*8 :: trten
      integer*8 :: tru
      integer*8 :: tru_emf
      integer*8 :: trten_out
      integer*8 :: trten_s
      integer*8 :: trflx_out
      integer*8 :: trflx_s
      integer*8 :: tru_out
      integer*8 :: tru_s
      integer*8 :: tru_emf_out
      integer*8 :: tru_emf_s
      integer*8 :: tr0_s
      real(r8) :: tscaleh
      real(r8) :: cush
      real(r8) :: pblh
      real(r8) :: exit_kinv1
      real(r8) :: dpsum
      real(r8) :: tkeavg
      real(r8) :: thvlmin
      real(r8) :: dpi
      real(r8) :: qtsrc
      real(r8) :: thvlsrc
      real(r8) :: thlsrc
      real(r8) :: usrc
      real(r8) :: vsrc
      real(r8) :: plcl
      real(r8) :: exit_klclmkx
      real(r8) :: thl0lcl
      real(r8) :: qt0lcl
      real(r8) :: thj
      real(r8) :: qvj
      real(r8) :: qlj
      real(r8) :: qij
      real(r8) :: qse
      real(r8) :: exit_conden
      real(r8) :: thv0lcl
      real(r8) :: cin
      real(r8) :: cinlcl
      real(r8) :: plfc
      real(r8) :: thvubot
      real(r8) :: thvutop
      real(r8) :: limit_cinlcl
      real(r8) :: limit_cin
      real(r8) :: exit_klfcmkx
      real(r8) :: cin_i
      real(r8) :: cinlcl_i
      real(r8) :: ke
      real(r8) :: kinv_o
      real(r8) :: klcl_o
      real(r8) :: klfc_o
      real(r8) :: plcl_o
      real(r8) :: plfc_o
      real(r8) :: tkeavg_o
      real(r8) :: thvlmin_o
      real(r8) :: qtsrc_o
      real(r8) :: thvlsrc_o
      real(r8) :: thlsrc_o
      real(r8) :: usrc_o
      real(r8) :: vsrc_o
      real(r8) :: thv0lcl_o
      real(r8) :: cin_f
      real(r8) :: cinlcl_f
      real(r8) :: del_CIN
      real(r8) :: alpha
      real(r8) :: del_cinlcl
      real(r8) :: precip
      real(r8) :: snow
      real(r8) :: rliq
      real(r8) :: cbmf
      real(r8) :: cnt
      real(r8) :: cnb
      real(r8) :: ufrcinvbase
      real(r8) :: ufrclcl
      real(r8) :: winvbase
      real(r8) :: wlcl
      real(r8) :: emfkbup
      real(r8) :: cbmflimit
      real(r8) :: ind_delcin
      real(r8) :: precip_out
      real(r8) :: precip_s
      real(r8) :: snow_out
      real(r8) :: snow_s
      real(r8) :: cush_inout
      real(r8) :: cush_s
      real(r8) :: cbmf_out
      real(r8) :: cbmf_s
      real(r8) :: rliq_out
      real(r8) :: rliq_s
      real(r8) :: cnt_out
      real(r8) :: cnt_s
      real(r8) :: cnb_out
      real(r8) :: cnb_s
      real(r8) :: cinh_out
      real(r8) :: cin_s
      real(r8) :: cinlclh_out
      real(r8) :: cinlcl_s
      real(r8) :: ufrcinvbase_out
      real(r8) :: ufrcinvbase_s
      real(r8) :: ufrclcl_out
      real(r8) :: ufrclcl_s
      real(r8) :: winvbase_out
      real(r8) :: winvbase_s
      real(r8) :: wlcl_out
      real(r8) :: wlcl_s
      real(r8) :: plcl_out
      real(r8) :: plcl_s
      real(r8) :: pinv_out
      real(r8) :: pinv_s
      real(r8) :: plfc_out
      real(r8) :: plfc_s
      real(r8) :: pbup_out
      real(r8) :: pbup_s
      real(r8) :: ppen_out
      real(r8) :: ppen_s
      real(r8) :: qtsrc_out
      real(r8) :: qtsrc_s
      real(r8) :: thlsrc_out
      real(r8) :: thlsrc_s
      real(r8) :: thvlsrc_out
      real(r8) :: thvlsrc_s
      real(r8) :: emfkbup_out
      real(r8) :: emfkbup_s
      real(r8) :: cbmflimit_out
      real(r8) :: cbmflimit_s
      real(r8) :: tkeavg_out
      real(r8) :: tkeavg_s
      real(r8) :: zinv_out
      real(r8) :: zinv_s
      real(r8) :: rcwp_out
      real(r8) :: rcwp_s
      real(r8) :: rlwp_out
      real(r8) :: rlwp_s
      real(r8) :: riwp_out
      real(r8) :: riwp_s
      real(r8) :: prel
      real(r8) :: thv0rel
      real(r8) :: wcrit
      real(r8) :: sigmaw
      real(r8) :: mu
      real(r8) :: rho0inv
      real(r8) :: mumin0
      real(r8) :: mulcl
      real(r8) :: mulclstar
      real(r8) :: erfc
      real(r8) :: mumin2
      real(r8) :: limit_ufrc
      real(r8) :: limit_cbmf
      real(r8) :: winv
      real(r8) :: ufrcinv
      real(r8) :: wtw
      real(r8) :: exit_wtw
      real(r8) :: wrel
      real(r8) :: exit_ufrc
      real(r8) :: uplus
      real(r8) :: vplus
      real(r8) :: pe
      real(r8) :: dpe
      real(r8) :: exne
      real(r8) :: thvebot
      real(r8) :: thle
      real(r8) :: qte
      real(r8) :: ue
      real(r8) :: ve
      real(r8) :: scaleh
      real(r8) :: thlue
      real(r8) :: qtue
      real(r8) :: wue
      real(r8) :: wtwb
      real(r8) :: thv0j
      real(r8) :: rho0j
      real(r8) :: qsat_arg
      real(r8) :: es
      real(r8) :: weight
      real(r8) :: estbl
      real(r8) :: qs
      real(r8) :: excess0
      real(r8) :: exql
      real(r8) :: exqi
      real(r8) :: thvj
      real(r8) :: excessu
      real(r8) :: xc
      real(r8) :: cridis
      real(r8) :: aquad
      real(r8) :: bquad
      real(r8) :: cquad
      real(r8) :: xsat
      real(r8) :: thlxsat
      real(r8) :: qtxsat
      real(r8) :: thvxsat
      real(r8) :: thv_x0
      real(r8) :: thv_x1
      real(r8) :: xs1
      real(r8) :: xs2
      real(r8) :: x_cu
      real(r8) :: x_en
      real(r8) :: ee2
      real(r8) :: ud2
      real(r8) :: delbog
      real(r8) :: bogtop
      real(r8) :: bogbot
      real(r8) :: drage
      real(r8) :: expfac
      real(r8) :: autodet
      real(r8) :: exit_wu
      real(r8) :: rhos0j
      real(r8) :: xc1
      real(r8) :: xc2
      real(r8) :: ppen
      real(r8) :: limit_ppen
      real(r8) :: thlu_top
      real(r8) :: qtu_top
      real(r8) :: exntop
      real(r8) :: forcedCu
      real(r8) :: limit_shcu
      real(r8) :: cldhgt
      real(r8) :: exit_cufilter
      real(r8) :: limit_emf
      real(r8) :: xsrc
      real(r8) :: xmean
      real(r8) :: xtop
      real(r8) :: xbot
      real(r8) :: thlten_sub
      real(r8) :: qtten_sub
      real(r8) :: qlten_sub
      real(r8) :: qiten_sub
      real(r8) :: nlten_sub
      real(r8) :: niten_sub
      real(r8) :: thl_prog
      real(r8) :: qt_prog
      real(r8) :: rainflx
      real(r8) :: snowflx
      real(r8) :: qlu_mid
      real(r8) :: qiu_mid
      real(r8) :: qlubelow
      real(r8) :: qiubelow
      real(r8) :: qlu_top
      real(r8) :: qiu_top
      real(r8) :: qc_lm
      real(r8) :: qc_im
      real(r8) :: nc_lm
      real(r8) :: nc_im
      real(r8) :: ql_emf_kbup
      real(r8) :: qi_emf_kbup
      real(r8) :: nl_emf_kbup
      real(r8) :: ni_emf_kbup
      real(r8) :: qlten_det
      real(r8) :: qiten_det
      real(r8) :: evpint_rain
      real(r8) :: evpint_snow
      real(r8) :: snowmlt
      real(r8) :: subsat
      real(r8) :: evprain
      real(r8) :: evpsnow
      real(r8) :: evplimit
      real(r8) :: evplimit_rain
      real(r8) :: evplimit_snow
      real(r8) :: tmp1
      real(r8) :: tmp2
      real(r8) :: limit_negcon
      real(r8) :: trmin
      real(r8) :: pdelx
      real(r8) :: dum
      real(r8) :: pdel
      real(r8) :: qcubelow
      real(r8) :: rcwp
      real(r8) :: rlwp
      real(r8) :: riwp
      real(r8) :: thl0bot
      real(r8) :: qt0bot
      real(r8) :: thl0top
      real(r8) :: qt0top
      integer :: kinv
      integer :: id_exit
      integer :: klcl
      integer :: klfc
      integer :: id_exit_ex
      integer :: krel
      integer :: kbup
      integer :: mkx

    end type param_uw_com_t1
    type(param_uw_com_t1) param_uw_com_s1(iend)

    type param_uw_t1
      integer*8 :: ptr_param_uw1
      integer :: iend
    end type param_uw_t1
    type(param_uw_t1) param_uw_s1
#endif
    param_uw_s1%ptr_param_uw1 = loc(param_uw_com_s1)
    param_uw_s1%iend = iend
    do i = 1, iend
      param_uw_com_s1(i)%zs0 = loc(zs0)
      param_uw_com_s1(i)%ps0 = loc(ps0)
      param_uw_com_s1(i)%p0 = loc(p0)
      param_uw_com_s1(i)%tke = loc(tke)
      param_uw_com_s1(i)%thvl0bot = loc(thvl0bot)
      param_uw_com_s1(i)%thvl0top = loc(thvl0top)
      param_uw_com_s1(i)%qt0 = loc(qt0)
      param_uw_com_s1(i)%u0 = loc(u0)
      param_uw_com_s1(i)%ssu0 = loc(ssu0)
      param_uw_com_s1(i)%v0 = loc(v0)
      param_uw_com_s1(i)%ssv0 = loc(ssv0)
      param_uw_com_s1(i)%trsrc = loc(trsrc)
      param_uw_com_s1(i)%thl0 = loc(thl0)
      param_uw_com_s1(i)%ssthl0 = loc(ssthl0)
      param_uw_com_s1(i)%ssqt0 = loc(ssqt0)
      param_uw_com_s1(i)%thv0bot = loc(thv0bot)
      param_uw_com_s1(i)%thv0top = loc(thv0top)
      param_uw_com_s1(i)%trsrc_o = loc(trsrc_o)
      param_uw_com_s1(i)%qv0 = loc(qv0)
      param_uw_com_s1(i)%qv0_o = loc(qv0_o)
      param_uw_com_s1(i)%ql0 = loc(ql0)
      param_uw_com_s1(i)%ql0_o = loc(ql0_o)
      param_uw_com_s1(i)%qi0 = loc(qi0)
      param_uw_com_s1(i)%qi0_o = loc(qi0_o)
      param_uw_com_s1(i)%t0 = loc(t0)
      param_uw_com_s1(i)%t0_o = loc(t0_o)
      param_uw_com_s1(i)%s0 = loc(s0)
      param_uw_com_s1(i)%s0_o = loc(s0_o)
      param_uw_com_s1(i)%u0_o = loc(u0_o)
      param_uw_com_s1(i)%v0_o = loc(v0_o)
      param_uw_com_s1(i)%qt0_o = loc(qt0_o)
      param_uw_com_s1(i)%thl0_o = loc(thl0_o)
      param_uw_com_s1(i)%thvl0 = loc(thvl0)
      param_uw_com_s1(i)%thvl0_o = loc(thvl0_o)
      param_uw_com_s1(i)%ssthl0_o = loc(ssthl0_o)
      param_uw_com_s1(i)%ssqt0_o = loc(ssqt0_o)
      param_uw_com_s1(i)%thv0bot_o = loc(thv0bot_o)
      param_uw_com_s1(i)%thv0top_o = loc(thv0top_o)
      param_uw_com_s1(i)%thvl0bot_o = loc(thvl0bot_o)
      param_uw_com_s1(i)%thvl0top_o = loc(thvl0top_o)
      param_uw_com_s1(i)%ssu0_o = loc(ssu0_o)
      param_uw_com_s1(i)%ssv0_o = loc(ssv0_o)
      param_uw_com_s1(i)%umf = loc(umf)
      param_uw_com_s1(i)%emf = loc(emf)
      param_uw_com_s1(i)%slflx = loc(slflx)
      param_uw_com_s1(i)%qtflx = loc(qtflx)
      param_uw_com_s1(i)%uflx = loc(uflx)
      param_uw_com_s1(i)%vflx = loc(vflx)
      param_uw_com_s1(i)%qvten = loc(qvten)
      param_uw_com_s1(i)%qlten = loc(qlten)
      param_uw_com_s1(i)%qiten = loc(qiten)
      param_uw_com_s1(i)%sten = loc(sten)
      param_uw_com_s1(i)%uten = loc(uten)
      param_uw_com_s1(i)%vten = loc(vten)
      param_uw_com_s1(i)%qrten = loc(qrten)
      param_uw_com_s1(i)%qsten = loc(qsten)
      param_uw_com_s1(i)%dwten = loc(dwten)
      param_uw_com_s1(i)%diten = loc(diten)
      param_uw_com_s1(i)%evapc = loc(evapc)
      param_uw_com_s1(i)%cufrc = loc(cufrc)
      param_uw_com_s1(i)%qcu = loc(qcu)
      param_uw_com_s1(i)%qlu = loc(qlu)
      param_uw_com_s1(i)%qiu = loc(qiu)
      param_uw_com_s1(i)%fer = loc(fer)
      param_uw_com_s1(i)%fdr = loc(fdr)
      param_uw_com_s1(i)%qc = loc(qc)
      param_uw_com_s1(i)%qc_l = loc(qc_l)
      param_uw_com_s1(i)%qc_i = loc(qc_i)
      param_uw_com_s1(i)%qtten = loc(qtten)
      param_uw_com_s1(i)%slten = loc(slten)
      param_uw_com_s1(i)%ufrc = loc(ufrc)
      param_uw_com_s1(i)%thlu = loc(thlu)
      param_uw_com_s1(i)%qtu = loc(qtu)
      param_uw_com_s1(i)%uu = loc(uu)
      param_uw_com_s1(i)%vu = loc(vu)
      param_uw_com_s1(i)%wu = loc(wu)
      param_uw_com_s1(i)%thvu = loc(thvu)
      param_uw_com_s1(i)%thlu_emf = loc(thlu_emf)
      param_uw_com_s1(i)%qtu_emf = loc(qtu_emf)
      param_uw_com_s1(i)%uu_emf = loc(uu_emf)
      param_uw_com_s1(i)%vu_emf = loc(vu_emf)
      param_uw_com_s1(i)%excessu_arr = loc(excessu_arr)
      param_uw_com_s1(i)%excess0_arr = loc(excess0_arr)
      param_uw_com_s1(i)%xc_arr = loc(xc_arr)
      param_uw_com_s1(i)%aquad_arr = loc(aquad_arr)
      param_uw_com_s1(i)%bquad_arr = loc(bquad_arr)
      param_uw_com_s1(i)%cquad_arr = loc(cquad_arr)
      param_uw_com_s1(i)%bogbot_arr = loc(bogbot_arr)
      param_uw_com_s1(i)%bogtop_arr = loc(bogtop_arr)
      param_uw_com_s1(i)%umf_out = loc(umf_out)
      param_uw_com_s1(i)%umf_s = loc(umf_s)
      param_uw_com_s1(i)%qvten_out = loc(qvten_out)
      param_uw_com_s1(i)%qvten_s = loc(qvten_s)
      param_uw_com_s1(i)%qlten_out = loc(qlten_out)
      param_uw_com_s1(i)%qlten_s = loc(qlten_s)
      param_uw_com_s1(i)%qiten_out = loc(qiten_out)
      param_uw_com_s1(i)%qiten_s = loc(qiten_s)
      param_uw_com_s1(i)%sten_out = loc(sten_out)
      param_uw_com_s1(i)%sten_s = loc(sten_s)
      param_uw_com_s1(i)%uten_out = loc(uten_out)
      param_uw_com_s1(i)%uten_s = loc(uten_s)
      param_uw_com_s1(i)%vten_out = loc(vten_out)
      param_uw_com_s1(i)%vten_s = loc(vten_s)
      param_uw_com_s1(i)%qrten_out = loc(qrten_out)
      param_uw_com_s1(i)%qrten_s = loc(qrten_s)
      param_uw_com_s1(i)%qsten_out = loc(qsten_out)
      param_uw_com_s1(i)%qsten_s = loc(qsten_s)
      param_uw_com_s1(i)%evapc_out = loc(evapc_out)
      param_uw_com_s1(i)%evapc_s = loc(evapc_s)
      param_uw_com_s1(i)%cufrc_out = loc(cufrc_out)
      param_uw_com_s1(i)%cufrc_s = loc(cufrc_s)
      param_uw_com_s1(i)%slflx_out = loc(slflx_out)
      param_uw_com_s1(i)%slflx_s = loc(slflx_s)
      param_uw_com_s1(i)%qtflx_out = loc(qtflx_out)
      param_uw_com_s1(i)%qtflx_s = loc(qtflx_s)
      param_uw_com_s1(i)%qcu_out = loc(qcu_out)
      param_uw_com_s1(i)%qcu_s = loc(qcu_s)
      param_uw_com_s1(i)%qlu_out = loc(qlu_out)
      param_uw_com_s1(i)%qlu_s = loc(qlu_s)
      param_uw_com_s1(i)%qiu_out = loc(qiu_out)
      param_uw_com_s1(i)%qiu_s = loc(qiu_s)
      param_uw_com_s1(i)%qc_out = loc(qc_out)
      param_uw_com_s1(i)%qc_s = loc(qc_s)
      param_uw_com_s1(i)%fer_out = loc(fer_out)
      param_uw_com_s1(i)%fer_s = loc(fer_s)
      param_uw_com_s1(i)%fdr_out = loc(fdr_out)
      param_uw_com_s1(i)%fdr_s = loc(fdr_s)
      param_uw_com_s1(i)%qtten_out = loc(qtten_out)
      param_uw_com_s1(i)%qtten_s = loc(qtten_s)
      param_uw_com_s1(i)%slten_out = loc(slten_out)
      param_uw_com_s1(i)%slten_s = loc(slten_s)
      param_uw_com_s1(i)%ufrc_out = loc(ufrc_out)
      param_uw_com_s1(i)%ufrc_s = loc(ufrc_s)
      param_uw_com_s1(i)%uflx_out = loc(uflx_out)
      param_uw_com_s1(i)%uflx_s = loc(uflx_s)
      param_uw_com_s1(i)%vflx_out = loc(vflx_out)
      param_uw_com_s1(i)%vflx_s = loc(vflx_s)
      param_uw_com_s1(i)%wu_out = loc(wu_out)
      param_uw_com_s1(i)%wu_s = loc(wu_s)
      param_uw_com_s1(i)%qtu_out = loc(qtu_out)
      param_uw_com_s1(i)%qtu_s = loc(qtu_s)
      param_uw_com_s1(i)%thlu_out = loc(thlu_out)
      param_uw_com_s1(i)%thlu_s = loc(thlu_s)
      param_uw_com_s1(i)%thvu_out = loc(thvu_out)
      param_uw_com_s1(i)%thvu_s = loc(thvu_s)
      param_uw_com_s1(i)%uu_out = loc(uu_out)
      param_uw_com_s1(i)%uu_s = loc(uu_s)
      param_uw_com_s1(i)%vu_out = loc(vu_out)
      param_uw_com_s1(i)%vu_s = loc(vu_s)
      param_uw_com_s1(i)%qtu_emf_out = loc(qtu_emf_out)
      param_uw_com_s1(i)%qtu_emf_s = loc(qtu_emf_s)
      param_uw_com_s1(i)%thlu_emf_out = loc(thlu_emf_out)
      param_uw_com_s1(i)%thlu_emf_s = loc(thlu_emf_s)
      param_uw_com_s1(i)%uu_emf_out = loc(uu_emf_out)
      param_uw_com_s1(i)%uu_emf_s = loc(uu_emf_s)
      param_uw_com_s1(i)%vu_emf_out = loc(vu_emf_out)
      param_uw_com_s1(i)%vu_emf_s = loc(vu_emf_s)
      param_uw_com_s1(i)%uemf_out = loc(uemf_out)
      param_uw_com_s1(i)%uemf_s = loc(uemf_s)
      param_uw_com_s1(i)%dwten_out = loc(dwten_out)
      param_uw_com_s1(i)%dwten_s = loc(dwten_s)
      param_uw_com_s1(i)%diten_out = loc(diten_out)
      param_uw_com_s1(i)%diten_s = loc(diten_s)
      param_uw_com_s1(i)%flxrain_out = loc(flxrain_out)
      param_uw_com_s1(i)%flxrain_s = loc(flxrain_s)
      param_uw_com_s1(i)%flxsnow_out = loc(flxsnow_out)
      param_uw_com_s1(i)%flxsnow_s = loc(flxsnow_s)
      param_uw_com_s1(i)%ntraprd_out = loc(ntraprd_out)
      param_uw_com_s1(i)%ntraprd_s = loc(ntraprd_s)
      param_uw_com_s1(i)%ntsnprd_out = loc(ntsnprd_out)
      param_uw_com_s1(i)%ntsnprd_s = loc(ntsnprd_s)
      param_uw_com_s1(i)%excessu_arr_out = loc(excessu_arr_out)
      param_uw_com_s1(i)%excessu_arr_s = loc(excessu_arr_s)
      param_uw_com_s1(i)%excess0_arr_out = loc(excess0_arr_out)
      param_uw_com_s1(i)%excess0_arr_s = loc(excess0_arr_s)
      param_uw_com_s1(i)%xc_arr_out = loc(xc_arr_out)
      param_uw_com_s1(i)%xc_arr_s = loc(xc_arr_s)
      param_uw_com_s1(i)%aquad_arr_out = loc(aquad_arr_out)
      param_uw_com_s1(i)%aquad_arr_s = loc(aquad_arr_s)
      param_uw_com_s1(i)%bquad_arr_out = loc(bquad_arr_out)
      param_uw_com_s1(i)%bquad_arr_s = loc(bquad_arr_s)
      param_uw_com_s1(i)%cquad_arr_out = loc(cquad_arr_out)
      param_uw_com_s1(i)%cquad_arr_s = loc(cquad_arr_s)
      param_uw_com_s1(i)%bogbot_arr_out = loc(bogbot_arr_out)
      param_uw_com_s1(i)%bogbot_arr_s = loc(bogbot_arr_s)
      param_uw_com_s1(i)%bogtop_arr_out = loc(bogtop_arr_out)
      param_uw_com_s1(i)%bogtop_arr_s = loc(bogtop_arr_s)
      param_uw_com_s1(i)%exns0 = loc(exns0)
      param_uw_com_s1(i)%dp0 = loc(dp0)
      param_uw_com_s1(i)%write = loc(write)
      param_uw_com_s1(i)%tre = loc(tre)
      param_uw_com_s1(i)%rei = loc(rei)
      param_uw_com_s1(i)%exn0 = loc(exn0)
      param_uw_com_s1(i)%xflx = loc(xflx)
      param_uw_com_s1(i)%uemf = loc(uemf)
      param_uw_com_s1(i)%comsub = loc(comsub)
      param_uw_com_s1(i)%nlten_sink = loc(nlten_sink)
      param_uw_com_s1(i)%niten_sink = loc(niten_sink)
      param_uw_com_s1(i)%uf = loc(uf)
      param_uw_com_s1(i)%vf = loc(vf)
      param_uw_com_s1(i)%qlten_sink = loc(qlten_sink)
      param_uw_com_s1(i)%qiten_sink = loc(qiten_sink)
      param_uw_com_s1(i)%flxrain = loc(flxrain)
      param_uw_com_s1(i)%flxsnow = loc(flxsnow)
      param_uw_com_s1(i)%ntraprd = loc(ntraprd)
      param_uw_com_s1(i)%ntsnprd = loc(ntsnprd)
      param_uw_com_s1(i)%qw0_in = loc(qw0_in)
      param_uw_com_s1(i)%qv0_star = loc(qv0_star)
      param_uw_com_s1(i)%ql0_star = loc(ql0_star)
      param_uw_com_s1(i)%qi0_star = loc(qi0_star)
      param_uw_com_s1(i)%s0_star = loc(s0_star)
      param_uw_com_s1(i)%trflx_d = loc(trflx_d)
      param_uw_com_s1(i)%trflx_u = loc(trflx_u)
      param_uw_com_s1(i)%dpdry0 = loc(dpdry0)
      param_uw_com_s1(i)%qv0_s = loc(qv0_s)
      param_uw_com_s1(i)%ql0_s = loc(ql0_s)
      param_uw_com_s1(i)%qi0_s = loc(qi0_s)
      param_uw_com_s1(i)%s0_s = loc(s0_s)
      param_uw_com_s1(i)%u0_s = loc(u0_s)
      param_uw_com_s1(i)%v0_s = loc(v0_s)
      param_uw_com_s1(i)%qt0_s = loc(qt0_s)
      param_uw_com_s1(i)%t0_s = loc(t0_s)
      param_uw_com_s1(i)%flxprc1_out = loc(flxprc1_out)
      param_uw_com_s1(i)%flxsnow1_out = loc(flxsnow1_out)
      param_uw_com_s1(i)%tr0 = loc(tr0)
      param_uw_com_s1(i)%tr0_o = loc(tr0_o)
      param_uw_com_s1(i)%sstr0 = loc(sstr0)
      param_uw_com_s1(i)%sstr0_o = loc(sstr0_o)
      param_uw_com_s1(i)%trflx = loc(trflx)
      param_uw_com_s1(i)%trten = loc(trten)
      param_uw_com_s1(i)%tru = loc(tru)
      param_uw_com_s1(i)%tru_emf = loc(tru_emf)
      param_uw_com_s1(i)%trten_out = loc(trten_out)
      param_uw_com_s1(i)%trten_s = loc(trten_s)
      param_uw_com_s1(i)%trflx_out = loc(trflx_out)
      param_uw_com_s1(i)%trflx_s = loc(trflx_s)
      param_uw_com_s1(i)%tru_out = loc(tru_out)
      param_uw_com_s1(i)%tru_s = loc(tru_s)
      param_uw_com_s1(i)%tru_emf_out = loc(tru_emf_out)
      param_uw_com_s1(i)%tru_emf_s = loc(tru_emf_s)
      param_uw_com_s1(i)%tr0_s = loc(tr0_s)
      param_uw_com_s1(i)%tscaleh = tscaleh(i)
      param_uw_com_s1(i)%cush = cush(i)
      param_uw_com_s1(i)%pblh = pblh(i)
      param_uw_com_s1(i)%kinv = kinv(i)
      param_uw_com_s1(i)%exit_kinv1 = exit_kinv1(i)
      if (id_exit(i) .eq. .true.) then
        param_uw_com_s1(i)%id_exit = 1
      else
        param_uw_com_s1(i)%id_exit = 0
      endif
      param_uw_com_s1(i)%dpsum = dpsum(i)
      param_uw_com_s1(i)%tkeavg = tkeavg(i)
      param_uw_com_s1(i)%thvlmin = thvlmin(i)
      param_uw_com_s1(i)%dpi = dpi(i)
      param_uw_com_s1(i)%qtsrc = qtsrc(i)
      param_uw_com_s1(i)%thvlsrc = thvlsrc(i)
      param_uw_com_s1(i)%thlsrc = thlsrc(i)
      param_uw_com_s1(i)%usrc = usrc(i)
      param_uw_com_s1(i)%vsrc = vsrc(i)
      param_uw_com_s1(i)%plcl = plcl(i)
      param_uw_com_s1(i)%klcl = klcl(i)
      param_uw_com_s1(i)%exit_klclmkx = exit_klclmkx(i)
      param_uw_com_s1(i)%thl0lcl = thl0lcl(i)
      param_uw_com_s1(i)%qt0lcl = qt0lcl(i)
      param_uw_com_s1(i)%thj = thj(i)
      param_uw_com_s1(i)%qvj = qvj(i)
      param_uw_com_s1(i)%qlj = qlj(i)
      param_uw_com_s1(i)%qij = qij(i)
      param_uw_com_s1(i)%qse = qse(i)
      param_uw_com_s1(i)%exit_conden = exit_conden(i)
      param_uw_com_s1(i)%thv0lcl = thv0lcl(i)
      param_uw_com_s1(i)%cin = cin(i)
      param_uw_com_s1(i)%cinlcl = cinlcl(i)
      param_uw_com_s1(i)%plfc = plfc(i)
      param_uw_com_s1(i)%klfc = klfc(i)
      param_uw_com_s1(i)%thvubot = thvubot(i)
      param_uw_com_s1(i)%thvutop = thvutop(i)
      param_uw_com_s1(i)%limit_cinlcl = limit_cinlcl(i)
      param_uw_com_s1(i)%limit_cin = limit_cin(i)
      param_uw_com_s1(i)%exit_klfcmkx = exit_klfcmkx(i)
      param_uw_com_s1(i)%cin_i = cin_i(i)
      param_uw_com_s1(i)%cinlcl_i = cinlcl_i(i)
      param_uw_com_s1(i)%ke = ke(i)
      param_uw_com_s1(i)%kinv_o = kinv_o(i)
      param_uw_com_s1(i)%klcl_o = klcl_o(i)
      param_uw_com_s1(i)%klfc_o = klfc_o(i)
      param_uw_com_s1(i)%plcl_o = plcl_o(i)
      param_uw_com_s1(i)%plfc_o = plfc_o(i)
      param_uw_com_s1(i)%tkeavg_o = tkeavg_o(i)
      param_uw_com_s1(i)%thvlmin_o = thvlmin_o(i)
      param_uw_com_s1(i)%qtsrc_o = qtsrc_o(i)
      param_uw_com_s1(i)%thvlsrc_o = thvlsrc_o(i)
      param_uw_com_s1(i)%thlsrc_o = thlsrc_o(i)
      param_uw_com_s1(i)%usrc_o = usrc_o(i)
      param_uw_com_s1(i)%vsrc_o = vsrc_o(i)
      param_uw_com_s1(i)%thv0lcl_o = thv0lcl_o(i)
      param_uw_com_s1(i)%cin_f = cin_f(i)
      param_uw_com_s1(i)%cinlcl_f = cinlcl_f(i)
      param_uw_com_s1(i)%del_CIN = del_CIN(i)
      param_uw_com_s1(i)%alpha = alpha(i)
      param_uw_com_s1(i)%del_cinlcl = del_cinlcl(i)
      param_uw_com_s1(i)%precip = precip(i)
      param_uw_com_s1(i)%snow = snow(i)
      param_uw_com_s1(i)%rliq = rliq(i)
      param_uw_com_s1(i)%cbmf = cbmf(i)
      param_uw_com_s1(i)%cnt = cnt(i)
      param_uw_com_s1(i)%cnb = cnb(i)
      param_uw_com_s1(i)%ufrcinvbase = ufrcinvbase(i)
      param_uw_com_s1(i)%ufrclcl = ufrclcl(i)
      param_uw_com_s1(i)%winvbase = winvbase(i)
      param_uw_com_s1(i)%wlcl = wlcl(i)
      param_uw_com_s1(i)%emfkbup = emfkbup(i)
      param_uw_com_s1(i)%cbmflimit = cbmflimit(i)
      param_uw_com_s1(i)%ind_delcin = ind_delcin(i)
      param_uw_com_s1(i)%precip_out = precip_out(i)
      param_uw_com_s1(i)%precip_s = precip_s(i)
      param_uw_com_s1(i)%snow_out = snow_out(i)
      param_uw_com_s1(i)%snow_s = snow_s(i)
      param_uw_com_s1(i)%cush_inout = cush_inout(i)
      param_uw_com_s1(i)%cush_s = cush_s(i)
      param_uw_com_s1(i)%cbmf_out = cbmf_out(i)
      param_uw_com_s1(i)%cbmf_s = cbmf_s(i)
      param_uw_com_s1(i)%rliq_out = rliq_out(i)
      param_uw_com_s1(i)%rliq_s = rliq_s(i)
      param_uw_com_s1(i)%cnt_out = cnt_out(i)
      param_uw_com_s1(i)%cnt_s = cnt_s(i)
      param_uw_com_s1(i)%cnb_out = cnb_out(i)
      param_uw_com_s1(i)%cnb_s = cnb_s(i)
      param_uw_com_s1(i)%cinh_out = cinh_out(i)
      param_uw_com_s1(i)%cin_s = cin_s(i)
      param_uw_com_s1(i)%cinlclh_out = cinlclh_out(i)
      param_uw_com_s1(i)%cinlcl_s = cinlcl_s(i)
      param_uw_com_s1(i)%ufrcinvbase_out = ufrcinvbase_out(i)
      param_uw_com_s1(i)%ufrcinvbase_s = ufrcinvbase_s(i)
      param_uw_com_s1(i)%ufrclcl_out = ufrclcl_out(i)
      param_uw_com_s1(i)%ufrclcl_s = ufrclcl_s(i)
      param_uw_com_s1(i)%winvbase_out = winvbase_out(i)
      param_uw_com_s1(i)%winvbase_s = winvbase_s(i)
      param_uw_com_s1(i)%wlcl_out = wlcl_out(i)
      param_uw_com_s1(i)%wlcl_s = wlcl_s(i)
      param_uw_com_s1(i)%plcl_out = plcl_out(i)
      param_uw_com_s1(i)%plcl_s = plcl_s(i)
      param_uw_com_s1(i)%pinv_out = pinv_out(i)
      param_uw_com_s1(i)%pinv_s = pinv_s(i)
      param_uw_com_s1(i)%plfc_out = plfc_out(i)
      param_uw_com_s1(i)%plfc_s = plfc_s(i)
      param_uw_com_s1(i)%pbup_out = pbup_out(i)
      param_uw_com_s1(i)%pbup_s = pbup_s(i)
      param_uw_com_s1(i)%ppen_out = ppen_out(i)
      param_uw_com_s1(i)%ppen_s = ppen_s(i)
      param_uw_com_s1(i)%qtsrc_out = qtsrc_out(i)
      param_uw_com_s1(i)%qtsrc_s = qtsrc_s(i)
      param_uw_com_s1(i)%thlsrc_out = thlsrc_out(i)
      param_uw_com_s1(i)%thlsrc_s = thlsrc_s(i)
      param_uw_com_s1(i)%thvlsrc_out = thvlsrc_out(i)
      param_uw_com_s1(i)%thvlsrc_s = thvlsrc_s(i)
      param_uw_com_s1(i)%emfkbup_out = emfkbup_out(i)
      param_uw_com_s1(i)%emfkbup_s = emfkbup_s(i)
      param_uw_com_s1(i)%cbmflimit_out = cbmflimit_out(i)
      param_uw_com_s1(i)%cbmflimit_s = cbmflimit_s(i)
      param_uw_com_s1(i)%tkeavg_out = tkeavg_out(i)
      param_uw_com_s1(i)%tkeavg_s = tkeavg_s(i)
      param_uw_com_s1(i)%zinv_out = zinv_out(i)
      param_uw_com_s1(i)%zinv_s = zinv_s(i)
      param_uw_com_s1(i)%rcwp_out = rcwp_out(i)
      param_uw_com_s1(i)%rcwp_s = rcwp_s(i)
      param_uw_com_s1(i)%rlwp_out = rlwp_out(i)
      param_uw_com_s1(i)%rlwp_s = rlwp_s(i)
      param_uw_com_s1(i)%riwp_out = riwp_out(i)
      param_uw_com_s1(i)%riwp_s = riwp_s(i)
      if (id_exit_ex(i) .eq. .true.) then
        param_uw_com_s1(i)%id_exit_ex = 1
      else
        param_uw_com_s1(i)%id_exit_ex = 0
      endif
      param_uw_com_s1(i)%krel = krel(i)
      param_uw_com_s1(i)%prel = prel(i)
      param_uw_com_s1(i)%thv0rel = thv0rel(i)
      param_uw_com_s1(i)%wcrit = wcrit(i)
      param_uw_com_s1(i)%sigmaw = sigmaw(i)
      param_uw_com_s1(i)%mu = mu(i)
      param_uw_com_s1(i)%rho0inv = rho0inv(i)
      param_uw_com_s1(i)%mumin0 = mumin0(i)
      param_uw_com_s1(i)%mulcl = mulcl(i)
      param_uw_com_s1(i)%mulclstar = mulclstar(i)
      param_uw_com_s1(i)%erfc = erfc(i)
      param_uw_com_s1(i)%mumin2 = mumin2(i)
      param_uw_com_s1(i)%limit_ufrc = limit_ufrc(i)
      param_uw_com_s1(i)%limit_cbmf = limit_cbmf(i)
      param_uw_com_s1(i)%winv = winv(i)
      param_uw_com_s1(i)%ufrcinv = ufrcinv(i)
      param_uw_com_s1(i)%wtw = wtw(i)
      param_uw_com_s1(i)%exit_wtw = exit_wtw(i)
      param_uw_com_s1(i)%wrel = wrel(i)
      param_uw_com_s1(i)%exit_ufrc = exit_ufrc(i)
      param_uw_com_s1(i)%uplus = uplus(i)
      param_uw_com_s1(i)%vplus = vplus(i)
      param_uw_com_s1(i)%pe = pe(i)
      param_uw_com_s1(i)%dpe = dpe(i)
      param_uw_com_s1(i)%exne = exne(i)
      param_uw_com_s1(i)%thvebot = thvebot(i)
      param_uw_com_s1(i)%thle = thle(i)
      param_uw_com_s1(i)%qte = qte(i)
      param_uw_com_s1(i)%ue = ue(i)
      param_uw_com_s1(i)%ve = ve(i)
      param_uw_com_s1(i)%scaleh = scaleh(i)
      param_uw_com_s1(i)%kbup = kbup(i)
      param_uw_com_s1(i)%thlue = thlue(i)
      param_uw_com_s1(i)%qtue = qtue(i)
      param_uw_com_s1(i)%wue = wue(i)
      param_uw_com_s1(i)%wtwb = wtwb(i)
      param_uw_com_s1(i)%thv0j = thv0j(i)
      param_uw_com_s1(i)%rho0j = rho0j(i)
      param_uw_com_s1(i)%qsat_arg = qsat_arg(i)
      param_uw_com_s1(i)%es = es(i)
      param_uw_com_s1(i)%weight = weight(i)
      param_uw_com_s1(i)%estbl = estbl(i)
      param_uw_com_s1(i)%qs = qs(i)
      param_uw_com_s1(i)%excess0 = excess0(i)
      param_uw_com_s1(i)%exql = exql(i)
      param_uw_com_s1(i)%exqi = exqi(i)
      param_uw_com_s1(i)%thvj = thvj(i)
      param_uw_com_s1(i)%excessu = excessu(i)
      param_uw_com_s1(i)%xc = xc(i)
      param_uw_com_s1(i)%cridis = cridis(i)
      param_uw_com_s1(i)%aquad = aquad(i)
      param_uw_com_s1(i)%bquad = bquad(i)
      param_uw_com_s1(i)%cquad = cquad(i)
      param_uw_com_s1(i)%xsat = xsat(i)
      param_uw_com_s1(i)%thlxsat = thlxsat(i)
      param_uw_com_s1(i)%qtxsat = qtxsat(i)
      param_uw_com_s1(i)%thvxsat = thvxsat(i)
      param_uw_com_s1(i)%thv_x0 = thv_x0(i)
      param_uw_com_s1(i)%thv_x1 = thv_x1(i)
      param_uw_com_s1(i)%xs1 = xs1(i)
      param_uw_com_s1(i)%xs2 = xs2(i)
      param_uw_com_s1(i)%x_cu = x_cu(i)
      param_uw_com_s1(i)%x_en = x_en(i)
      param_uw_com_s1(i)%ee2 = ee2(i)
      param_uw_com_s1(i)%ud2 = ud2(i)
      param_uw_com_s1(i)%delbog = delbog(i)
      param_uw_com_s1(i)%bogtop = bogtop(i)
      param_uw_com_s1(i)%bogbot = bogbot(i)
      param_uw_com_s1(i)%drage = drage(i)
      param_uw_com_s1(i)%expfac = expfac(i)
      param_uw_com_s1(i)%autodet = autodet(i)
      param_uw_com_s1(i)%exit_wu = exit_wu(i)
      param_uw_com_s1(i)%rhos0j = rhos0j(i)
      param_uw_com_s1(i)%xc1 = xc1(i)
      param_uw_com_s1(i)%xc2 = xc2(i)
      param_uw_com_s1(i)%ppen = ppen(i)
      param_uw_com_s1(i)%limit_ppen = limit_ppen(i)
      param_uw_com_s1(i)%thlu_top = thlu_top(i)
      param_uw_com_s1(i)%qtu_top = qtu_top(i)
      param_uw_com_s1(i)%exntop = exntop(i)
      param_uw_com_s1(i)%forcedCu = forcedCu(i)
      param_uw_com_s1(i)%limit_shcu = limit_shcu(i)
      param_uw_com_s1(i)%cldhgt = cldhgt(i)
      param_uw_com_s1(i)%exit_cufilter = exit_cufilter(i)
      param_uw_com_s1(i)%limit_emf = limit_emf(i)
      param_uw_com_s1(i)%xsrc = xsrc(i)
      param_uw_com_s1(i)%xmean = xmean(i)
      param_uw_com_s1(i)%xtop = xtop(i)
      param_uw_com_s1(i)%xbot = xbot(i)
      param_uw_com_s1(i)%thlten_sub = thlten_sub(i)
      param_uw_com_s1(i)%qtten_sub = qtten_sub(i)
      param_uw_com_s1(i)%qlten_sub = qlten_sub(i)
      param_uw_com_s1(i)%qiten_sub = qiten_sub(i)
      param_uw_com_s1(i)%nlten_sub = nlten_sub(i)
      param_uw_com_s1(i)%niten_sub = niten_sub(i)
      param_uw_com_s1(i)%thl_prog = thl_prog(i)
      param_uw_com_s1(i)%qt_prog = qt_prog(i)
      param_uw_com_s1(i)%rainflx = rainflx(i)
      param_uw_com_s1(i)%snowflx = snowflx(i)
      param_uw_com_s1(i)%qlu_mid = qlu_mid(i)
      param_uw_com_s1(i)%qiu_mid = qiu_mid(i)
      param_uw_com_s1(i)%qlubelow = qlubelow(i)
      param_uw_com_s1(i)%qiubelow = qiubelow(i)
      param_uw_com_s1(i)%qlu_top = qlu_top(i)
      param_uw_com_s1(i)%qiu_top = qiu_top(i)
      param_uw_com_s1(i)%qc_lm = qc_lm(i)
      param_uw_com_s1(i)%qc_im = qc_im(i)
      param_uw_com_s1(i)%nc_lm = nc_lm(i)
      param_uw_com_s1(i)%nc_im = nc_im(i)
      param_uw_com_s1(i)%ql_emf_kbup = ql_emf_kbup(i)
      param_uw_com_s1(i)%qi_emf_kbup = qi_emf_kbup(i)
      param_uw_com_s1(i)%nl_emf_kbup = nl_emf_kbup(i)
      param_uw_com_s1(i)%ni_emf_kbup = ni_emf_kbup(i)
      param_uw_com_s1(i)%qlten_det = qlten_det(i)
      param_uw_com_s1(i)%qiten_det = qiten_det(i)
      param_uw_com_s1(i)%evpint_rain = evpint_rain(i)
      param_uw_com_s1(i)%evpint_snow = evpint_snow(i)
      param_uw_com_s1(i)%snowmlt = snowmlt(i)
      param_uw_com_s1(i)%subsat = subsat(i)
      param_uw_com_s1(i)%evprain = evprain(i)
      param_uw_com_s1(i)%evpsnow = evpsnow(i)
      param_uw_com_s1(i)%evplimit = evplimit(i)
      param_uw_com_s1(i)%evplimit_rain = evplimit_rain(i)
      param_uw_com_s1(i)%evplimit_snow = evplimit_snow(i)
      param_uw_com_s1(i)%tmp1 = tmp1(i)
      param_uw_com_s1(i)%tmp2 = tmp2(i)
      param_uw_com_s1(i)%limit_negcon = limit_negcon(i)
      param_uw_com_s1(i)%trmin = trmin(i)
      param_uw_com_s1(i)%pdelx = pdelx(i)
      param_uw_com_s1(i)%dum = dum(i)
      param_uw_com_s1(i)%pdel = pdel(i)
      param_uw_com_s1(i)%qcubelow = qcubelow(i)
      param_uw_com_s1(i)%rcwp = rcwp(i)
      param_uw_com_s1(i)%rlwp = rlwp(i)
      param_uw_com_s1(i)%riwp = riwp(i)
      param_uw_com_s1(i)%thl0bot = thl0bot(i)
      param_uw_com_s1(i)%qt0bot = qt0bot(i)
      param_uw_com_s1(i)%thl0top = thl0top(i)
      param_uw_com_s1(i)%qt0top = qt0top(i)
      param_uw_com_s1(i)%mkx = mkx
    end do
